user_management/urls.py
from django.urls import path
from .views import login, logout, registration, edit_user

urlpatterns = [
    path('login/', login),
    path('logout/', logout),
    path('registration/', registration),
    path('edit/', edit_user),
]

video/urls.py
from django.urls import path
from .views import VideoDetailView, VideoListView, VideoChannelListView, VideoCreateView, VideoDeleteView, VideoUpdateView

urlpatterns = [
    path('<str:username>', VideoChannelListView.as_view(), name='video_channel'),
    path('video/<int:pk>', VideoDetailView.as_view(), name='video_detail'),
    path('video/delete/<int:pk>', VideoDeleteView.as_view(), name='video_delete'),
    path('video/update/<int:pk>', VideoUpdateView.as_view(), name='video_edit'),
    path('add_video/', VideoCreateView.as_view(), name='add_video'),
    path('', VideoListView.as_view(), name='main_page'),
]

video_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user_management.urls')),
    path('', include('video.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/models.py
from django.db import models

# Create your models here.

video/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from video_service import settings


class Video(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    description = models.TextField(max_length=1000)
    author = models.ForeignKey(User, related_name='videos', on_delete=models.CASCADE, db_index=True)
    video = models.FileField(upload_to="video")
    preview = models.ImageField(upload_to='preview', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.video.name))
        os.remove(os.path.join(settings.MEDIA_ROOT, self.preview.name))
        super().delete(*args, **kwargs)


class Comment(models.Model):
    video = models.ForeignKey(Video, related_name='comments', on_delete=models.CASCADE, db_index=True)
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE, db_index=True)
    text = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)

user_management/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

video/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Video, Comment


class VideoCreateForm(ModelForm):

    class Meta:
        model = Video
        fields = ('title', 'description', 'video', 'preview')


class VideoUpdateForm(ModelForm):

    class Meta:
        model = Video
        fields = ('title', 'description', 'preview')


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

user_management/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import Http404, HttpResponseRedirect
from .forms import RegistrationForm, UserEditForm
from django.contrib.auth.decorators import login_required


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)

        if user:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            context = {'username': username, 'errors': True}
            return render(request, 'index.html', context)
    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            user = auth.authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])

            if user:
                auth.login(request, user)
                return HttpResponseRedirect('/')

            return HttpResponseRedirect('/')
        context = {'form': form}
        return render(request, 'registration.html', context)
    context = {'form': RegistrationForm()}
    return render(request, 'registration.html', context)


@login_required()
def edit_user(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/user/edit/')
        context = {'form': form}
        return render(request, 'edit_user.html', context)
    form = UserEditForm(instance=request.user)
    context = {'form': form}
    return render(request, 'edit_user.html', context)

video/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Video, Comment
from .forms import VideoCreateForm, VideoUpdateForm, CommentForm


class VideoDetailView(DetailView):
    template_name = 'video_page.html'
    model = Video

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        comments = Comment.objects.filter(video=self.get_object()).order_by('-created_at')
        data['comments'] = comments
        if self.request.user.is_authenticated:
            data['comment_form'] = CommentForm(instance=self.request.user)

        return data

    def post(self, request, *args, **kwargs):
        new_comment = Comment(text=request.POST.get('text'),
                              author=self.request.user,
                              video=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)


class VideoListView(ListView):
    model = Video
    paginate_by = 20
    template_name = 'main.html'
    ordering = '-created_at'


class VideoChannelListView(ListView):
    paginate_by = 20
    template_name = 'video_channel.html'

    def get_queryset(self):
        self.author = self.kwargs['username']
        return Video.objects.filter(author__username=self.author).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        return context


class VideoCreateView(CreateView):
    template_name = 'add_video.html'
    model = Video
    form_class = VideoCreateForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return HttpResponseRedirect(f'/{self.request.user}')


class VideoDeleteView(DeleteView):
    model = Video
    template_name = "video_confirm_delete.html"

    def get_object(self, queryset=None):
        obj = super(VideoDeleteView, self).get_object()
        if not obj.author == self.request.user:
            raise Http404
        return obj

    def get_success_url(self):
        return reverse('video_channel', kwargs={'username': self.request.user})


class VideoUpdateView(UpdateView):
    template_name = 'edit_video.html'
    model = Video
    form_class = VideoUpdateForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return HttpResponseRedirect(f'/{self.request.user}')

templates/base.html
{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>

    </header>
    <nav>
        {% include 'navbar.html' %}
    </nav>
    <section>
        {% block content %}
        {% endblock %}
    </section>
    <footer>

    </footer>
    <script>
    /* When the user clicks on the button,
    toggle between hiding and showing the dropdown content */
    function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function(e) {
        if (!e.target.matches('.dropbtn')) {
            var myDropdown = document.getElementById("myDropdown");
            if (myDropdown.classList.contains('show')) {
                myDropdown.classList.remove('show');
            }
        }
    }
    </script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
Home page
{% endblock %}

templates/navbar.html
{% load static %}
<div class="logo">
    <a href="/">
        На главную
    </a>
</div>

<div class="dropdown">
    <img src="{% static 'images/user.png' %}" class="dropbtn">
    <div class="dropdown-content">
        {% if user.is_authenticated %}
        <a href="/{{ user.username }}">Канал</a>
        <a href="/user/edit/">Редактировать профиль</a>
        <a href="/user/logout/">Выйти</a>
        {% else %}
        <a href="/user/login/">Войти</a>
        <a href="/user/registration/">Регистрация</a>
        {% endif %}
    </div>
</div>

user_management/templates/edit_user.html
{% extends 'base.html' %}

{% block title %}
Edit User
{% endblock %}

{% block content %}
    {% if reg_errors %}
        <ul>
            {% for value in reg_errors.values %}
                <p>
                    {{ value }}
                </p>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post" role="form" action="/user/edit/">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" class="btn btn-dark" value="Сохранить изменения">
    </form>
{% endblock %}

user_management/templates/login.html
{% extends "base.html" %}

{% block title %}
Login Page
{% endblock %}

{% block content %}
<form method="post" action="/user/login/">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <input class="form-control form-control-sm" type="text" name="username" value="" placeholder="Имя пользователя">
            <input class="form-control form-control-sm" type="password" name="password" value="" placeholder="Пароль">
        </div>
        <div class="col">
            <button type="submit" class="btn btn-dark">Войти</button>
        </div>
    </div>
</form>
{% if errors %}
    неправильное сочитание логин/пароль
{% endif %}
{% endblock %}

user_management/templates/registration.html
{% extends 'base.html' %}

{% block title %}
Registration
{% endblock %}

{% block content %}
    {% if reg_errors %}
        <ul>
            {% for value in reg_errors.values %}
                <p>
                    {{ value }}
                </p>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post" role="form" action="/user/registration/">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" class="btn btn-dark" value="Зарегистрироваться">
    </form>
{% endblock %}

video/templates/add_video.html
{% extends 'base.html' %}

{% block title %}
Add Video
{% endblock %}

{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
<!--        <table>-->
<!--            {{ form.as_table }}-->
<!--        </table>-->
        {% include 'form_base.html' %}
        <input type="submit" class="btn btn-dark" value="Добавить">
    </form>
{% endblock %}

video/templates/edit_video.html
{% extends 'base.html' %}

{% block title %}
Edit Video
{% endblock %}

{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" class="btn btn-dark" value="Сохранить">
    </form>
{% endblock %}

video/templates/main.html
{% extends 'base.html' %}

{% block title %}
    Video Service
{% endblock %}

{% block content %}
    {% for video in video_list %}
        <div class="video-overview">
            <div class="video-preview">
                <a href="{% url 'video_detail' video.id %}">
                    <img src="{{ video.preview }}" width="350" height="240">
                </a>
            </div>
            <a href="{% url 'video_detail' video.id %}">
                <h5>{{ video.title }}</h5>
            </a>
            <a href="{% url 'video_channel' video.author %}">
                <h6>{{ video.author }}</h6>
            </a>
            {{ video.created_at }}
        </div>
    {% endfor %}
{% endblock %}

video/templates/video_channel.html
{% extends 'base.html' %}

{% block title %}
    {{ author }} - Video Service
{% endblock %}

{% block content %}
    {% for video in video_list %}
        <div class="video-overview">
            <div class="video-preview">
                <a href="{% url 'video_detail' video.id %}">
                    <img src="{{ video.preview }}" width="350" height="240">
                </a>
            </div>
            <a href="{% url 'video_detail' video.id %}">
                <h5>{{ video.title }}</h5>
            </a>
            <a href="{% url 'video_channel' video.author %}">
                <h6>{{ video.author }}</h6>
            </a>
            {{ video.created_at }}
            {% if user == video.author %}
            <a href="{% url 'video_edit' video.id %}">Edit</a>
            <a href="{% url 'video_delete' video.id %}">Delete</a>
            {% endif %}
        </div>
    {% endfor %}

    <a href="{% url 'add_video' %}">Добавить новое видео</a>
{% endblock %}

video/templates/video_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

video/templates/video_page.html
{% extends "base.html" %}

{% block title %}
    {{ video.title }} | Video Service
{% endblock %}

{% block content %}
    <div class="video">
        <video controls>
          <source src="/{{ video.video }}" type="video/mp4">
          Your browser doesn't support HTML5 video tag.
        </video>
    </div>
    {% if user == video.author %}
    <a href="{% url 'video_edit' video.id %}">Edit</a>
    <a href="{% url 'video_delete' video.id %}">Delete</a>
    {% endif %}
    <h1>{{ video.title }}</h1>
    <h5>{{ video.author }}</h5>
    <h6>{{ video.created_at }}</h6>
    {{ video.description }}

    <div class="add-comment">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ comment_form.as_table }}
            <input type="submit" class="btn btn-dark" value="Добавить">
        </form>
    </div>
    <div class="comment-list">
        {% for comment in comments %}
            <div class="comment">
                <b>{{ comment.author }}</b>
                <i><small>{{ comment.created_at }}</small></i>
                <h6>{{ comment.text }}</h6>
                {% if user == comment.author %}
                    <a href="">Изменить</a>
                    <a href="">Удалить</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>

{% endblock %}